import { Inter } from "next/font/google";
import "./globals.css";
import SupabaseProvider from "@/app/providers/SupabaseProvider";
import UserProvider from "@/app/providers/UserProvider";
import ModalProviders from "@/app/providers/ModalProviders";
import Header from "@/app/components/Header";
import NavBar from "@/app/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <SupabaseProvider>
        <UserProvider>
          <ModalProviders />
          <Header />
          <div className="flex">
            <NavBar />
            <div className="ml-64 mt-16 p-4 flex-1">{children}</div>
          </div>
        </UserProvider>
      </SupabaseProvider>
      </body>
      </html>
  );
}
