import React from 'react';

const TermsOfUse = () => {
    return (
        <div style={{ maxWidth: '800px', margin: '40px auto', padding: '20px', fontFamily: 'Arial, sans-serif', lineHeight: '1.8', color: '#333' }}>
            <h1 style={{ fontSize: '2rem', color: '#2c3e50', marginBottom: '20px' }}>Terms of Use</h1>

            <p>Welcome to our Website, <a href="http://www.SavewellFinance.com" style={{ color: '#007BFF', textDecoration: 'underline' }}>www.SavewellFinance.com</a> (the “Site”). The term “SavewellFinance.com”, “us” or “our” refers to Savewell Finance, the legal name of the owner of the Site. The term “you” refers to the user or viewer of our Site. The following terms of use in this agreement (the “Agreement”) describe the terms and conditions applicable to your use of the Site and any Products or Referral Service offered by us through the Site (the “Products” and “Referral Service”). Please review the Agreement and its corresponding privacy policy (the “Privacy Policy”), which is incorporated by reference, carefully, as by using the Site, you agree to comply with and be bound by its terms. If you do not agree to these terms, you may not use or access the Site or Products or Referral Service.</p>

            <h2 style={{ fontSize: '1.6rem', color: '#2c3e50', marginBottom: '15px' }}>Acceptance of Agreement; Entire Agreement</h2>
            <p>You agree that this Agreement constitutes the entire and only agreement between SavewellFinance.com and you, and supersedes all prior or contemporaneous agreements, representations, warranties and understandings, if any, with respect to the Site, the content, or Products and Referral Service provided by or through the Site, and the subject matter of this Agreement. This Agreement may be amended at any time without notice to you. The latest Agreement will be posted on the Site, and you should review this Agreement prior to using the Site.</p>

            <h2 style={{ fontSize: '1.6rem', color: '#2c3e50', marginBottom: '15px' }}>Financial Products and Services</h2>
            <p>You understand that through the Site, we offer both the Products and the Referral Service, which provides an online information portal, articles, podcasts, calculators, financial planning tools and marketplace where you can research and compare solutions in a number of different categories.</p>
            <p>The Products offered by SavewellFinance.com may include both free tools and user paid tools or packaged financial guidance. You acknowledge and agree that the content, calculators & tools on SavewellFinance.com are for informational and educational purposes only and should not be construed as professional financial advice. SavewellFinance.com includes tools that individuals can use on their own behalf to help think through their future plans, but should not be acted upon as a complete financial plan. We recommend that you seek the advice of a financial services professional who has a fiduciary relationship with you before making any type of investment or significant financial decision. SavewellFinance.com strives to keep its information & tools accurate and up to date. This information presented is based on objective analysis, but it may not be the same that you find on a particular financial institution, service provider or specific product’s site. All content, tools, financial products, calculations, estimates, forecasts, comparison shopping products and services are presented without warranty.</p>

            <h2 style={{ fontSize: '1.6rem', color: '#2c3e50', marginBottom: '15px' }}>Use of the Site and Service</h2>
            <p>You certify to SavewellFinance.com that: (i) you are eighteen (18) years of age or older; (ii) you assume complete responsibility for the use of the Products by any minors; (iii) you agree that all information you have submitted to SavewellFinance.com, online or otherwise, is complete and accurate, and that you have not intentionally submitted false information on or through the Site or Products or Referral Service; and (iv) your use of the Site and Products or Referral Service is subject to all applicable federal, state, and local laws and regulations.</p>
            <p>All calculators and tools on the SavewellFinance.com site are designed to be informational and educational tools only and do not constitute investment advice. We recommend that you seek the advice of a financial services professional before making any type of investment. We also encourage you to review your financial plans periodically as your financial circumstances change. These tools & models are provided as a rough approximation of future financial performance. The results presented by these calculators are hypothetical and may not reflect the actual growth of your own investments. SavewellFinance.com and its affiliates are not responsible for the consequences of any decisions or actions taken in reliance upon or as a result of the information provided by these tools. SavewellFinance.com is not responsible for any human or mechanical errors or omissions.</p>
            <p>The Community sections including Answers on the SavewellFinance.com site are designed to be informational and educational only. Community postings do not constitute investment advice; nor do they reflect the opinions or policies of SavewellFinance.com. Community posts are solely the opinion and responsibility of the person posting the message. We strongly recommend that you seek the advice of a financial services professional before making any type of investment. We also encourage you to review your investment strategy periodically as your financial circumstances change. SavewellFinance.com and its affiliates are not responsible for the consequences of any decisions or actions taken in reliance upon or as a result of the information provided by registered users in their postings on the SavewellFinance.com website. SavewellFinance.com is not responsible for any human or mechanical errors or omissions.</p>
            <p>If you post User Content to the Site, unless we indicate otherwise, you grant Company and its affiliates a nonexclusive, royalty-free, perpetual, irrevocable and fully sublicensable right to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform and display such User Content throughout the world in any media. You grant Company and its affiliates and sublicensees the right to use the name that you submit in connection with such User Content, if they choose. You represent and warrant that (a) you own and control all of the rights to the User Content that you post or you otherwise have the right to post such User Content to the Site and to grant the rights granted herein; (b) the User Content is accurate and not misleading; and (c) use and posting of the User Content you supply does not violate these Site Terms and will not violate any rights of or cause injury to any person or entity.</p>

            <h2 style={{ fontSize: '1.6rem', color: '#2c3e50', marginBottom: '15px' }}>Prohibited Conduct</h2>
            <p>As a party to this Agreement, you agree not to: (i) submit, transmit, promote or distribute information or content that is illegal; (ii) submit, transmit or facilitate the distribution of information or content that is abusive, harmful, racially or ethnically offensive, vulgar, sexually explicit, defamatory, infringing, invasive of personal privacy or publicity rights, or in a rational person’s view, objectionable; (iii) attempt to interfere with, compromise the system integrity or security or decipher any transmissions to or from the servers running the Products or Referral Service; (iv) take any action that imposes, or may impose at our sole discretion an unreasonable or disproportionately large load on our infrastructure; (v) transmit or submit invalid data, viruses, worms, or other software agents through the Products or Referral Service; (vi) use any spider, robot, scraper or other automated access the Products or Referral Service for any purpose without our express written permission; (vii) impersonate a different person or otherwise misrepresent your affiliation with a person or entity, conduct fraud, hide or attempt to hide your identity; (viii) submit, post, upload, email, transmit or otherwise make available any content or information that you do not have a right to make available under any law or under contractual or fiduciary relationships; (ix) obstruct the proper working of the Products or Referral Service; or (x) circumvent the measures we may use to prevent or restrict access to the Products or Referral Service; (xi) submit, post, upload, email, transmit or otherwise make available any email content from private parties; (xii) submit, post, upload, email, transmit or otherwise make available content or posts that solicit purchases or use of merchandise, auctions, services or commercial Web sites, including offers to trade, “wanted” posts, or charitable solicitations; (xiii) submit, post, upload, email, transmit or otherwise make available any content including another individual’s contact information and/or email address.</p>

            <h2 style={{ fontSize: '1.6rem', color: '#2c3e50', marginBottom: '15px' }}>Privacy Policy</h2>
            <p>SavewellFinance.com respects and acknowledges the importance of your privacy. Personal information submitted in connection with the Products or Referral Service is subject to our Privacy Policy. For more information, see our full <a href="http://savewellfinance.com/privacy" style={{ color: '#007BFF', textDecoration: 'underline' }}>Privacy Policy</a>.</p>

            <h2 style={{ fontSize: '1.6rem', color: '#2c3e50', marginBottom: '15px' }}>Trademarks, Copyrights and other Intellectual Property</h2>
            <p>The content contained on this Website is owned or licensed by SavewellFinance.com and its third-party information providers and is protected by applicable copyrights, trademarks, service marks, and/or other intellectual property rights. Such content is solely for your personal, non-commercial use. Accordingly, you may not copy, distribute, modify, post, frame or deep link this Website, including any text, graphics, video, audio, software code, user interface design or logos. You may download material displayed on this Website for your personal use provided you also retain all copyright and other proprietary notices contained on the materials. You may not distribute, modify, transmit, reuse, repost, or use the content of this Website for public or commercial purposes, including all text, images, audio, and video, without SavewellFinance.com’s written permission. Modification or use of the materials for any other purpose violates SavewellFinance.com’s intellectual property rights.</p>
            <p>All trademarks, service marks, trade names, and logos displayed on this Website are proprietary to SavewellFinance.com and/or their respective owners. Nothing contained on this Website should be construed as granting, by implication, estoppel, or otherwise, any license or right to use any trademark displayed on this Website without the written permission of SavewellFinance.com or such other third party that may own the trademark displayed on this Website. Your use of the trademarks displayed on this Website, except as provided herein, is strictly prohibited.</p>
            <p>The use of the images displayed on this Website by you, or anyone else authorized by you, is prohibited. Any unauthorized use of the images may violate copyright laws, trademark laws, and the laws of privacy and publicity, and communications, as well as other regulations and statutes. If you download any information from this Website, you agree that you will not copy it or remove or obscure any copyright or other notices or legends contained in any such information.</p>

            <h2 style={{ fontSize: '1.6rem', color: '#2c3e50', marginBottom: '15px' }}>Proprietary Rights</h2>
            <p>You acknowledge and agree that the Products or Referral Service and any necessary software used in connection with the Products or Referral Service (the “Software”) contain proprietary and confidential information that is protected by applicable intellectual property and other laws. You also agree that all materials and/or content, including, but not limited to, articles, graphics, screen shots, logos, text, drawings and other files on the Site or as part of the Products or Referral Service are copyrights, trademarks, service marks, patents or other proprietary rights of SavewellFinance.com or their respective intellectual property owners. Unless expressly authorized by SavewellFinance.com, you agree not to modify, copy, reproduce, sell, distribute or create derivative works based on or contained within the Products or Referral Service or the Software, in whole or in part.</p>
            <p>SavewellFinance.com grants you a personal, non-transferable, non-sublicensable and non-exclusive license to use the code of this Site, the Products or Referral Service and the Software on a single computer; provided that you do not copy, modify, create a derivative work of, reverse engineer, decompile, reverse assemble or otherwise attempt to discover any source code, assign, sell, sublicense, grant a security interest in or otherwise transfer any right in the Software. You agree not to modify the Site or Software in any manner or form, or to use modified versions of the Site or Software, including, without limitation, for the purpose of obtaining unauthorized access to the Products or Referral Service by any means other than through the interface that is provided by SavewellFinance.com for use in accessing the Products or Referral Service.</p>

            <h2 style={{ fontSize: '1.6rem', color: '#2c3e50', marginBottom: '15px' }}>Links</h2>
            <p>SavewellFinance.com may provide links to third party websites; however, since SavewellFinance.com does not control these websites, you acknowledge and agree that SavewellFinance.com is not responsible for the availability of such external websites, and does not endorse and is not responsible or liable for any information, content, advertising, products, whether financial or otherwise, or other materials on or available from such websites. You also acknowledge and agree that SavewellFinance.com shall not be responsible or liable, directly or indirectly, for any loss or damage caused or alleged to be caused by or in connection with use of or reliance on any such content, products, goods or services available on or through any such website.</p>

            <h2 style={{ fontSize: '1.6rem', color: '#2c3e50', marginBottom: '15px' }}>Indemnification</h2>
            <p>You agree to indemnify and hold SavewellFinance.com, its subsidiaries, affiliates, agents, shareholders, officers, contractors, vendors and employees harmless from any claim or demand, including reasonable attorneys’ fees, made by any third party due to or arising out of your use of the Site, the Products or Referral Service or any Software, the violation of the Agreement by you, or the infringement by you, or any other user of the Site, the Service or Software using your computer, of any intellectual property or other right of any person or entity. SavewellFinance.com reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you.</p>

            <h2 style={{ fontSize: '1.6rem', color: '#2c3e50', marginBottom: '15px' }}>No Warranty</h2>
            <p>SavewellFinance.com PROVIDES THE SITE, THE PRODUCTS OR REFERRAL SERVICE, INCLUDING ANY SOFTWARE ASSOCIATED THEREWITH, “AS IS,” “WITH ALL FAULTS” AND “AS AVAILABLE,” AND THE ENTIRE RISK AS TO SATISFACTORY QUALITY, PERFORMANCE, RESULT, ACCURACY, AND EFFORT IS WITH YOU. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, SavewellFinance.com MAKES NO REPRESENTATIONS, WARRANTIES OR CONDITIONS, EXPRESS OR IMPLIED. SavewellFinance.com DISCLAIMS ANY AND ALL WARRANTIES OR CONDITIONS, EXPRESS, STATUTORY AND IMPLIED, INCLUDING WITHOUT LIMITATION: (i) WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, WORKMANLIKE EFFORT, TITLE, QUIET ENJOYMENT, NO ENCUMBRANCES, NO LIENS AND NON-INFRINGEMENT; (ii) WARRANTIES OR CONDITIONS ARISING THROUGH COURSE OF DEALING OR USAGE OF TRADE; AND (iii) WARRANTIES OR CONDITIONS THAT ACCESS TO OR USE OF THE PRODUCTS OR REFERRAL SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE. THERE ARE NO WARRANTIES THAT EXTEND BEYOND THE FACE OF THIS AGREEMENT.</p>

            <h2 style={{ fontSize: '1.6rem', color: '#2c3e50', marginBottom: '15px' }}>Limitation of Liability</h2>
            <p>IN NO EVENT WILL SavewellFinance.com BE LIABLE FOR ANY DAMAGES, INCLUDING WITHOUT LIMITATION ANY INDIRECT, SPECIAL, CONSEQUENTIAL, INCIDENTAL, OR PUNITIVE DAMAGES ARISING OUT OF, BASED ON, OR RESULTING FROM THIS AGREEMENT OR YOUR USE OF THE SITE, THE PRODUCTS OR REFERRAL SERVICE OR ANY SOFTWARE ASSOCIATED THEREWITH, EVEN IF SavewellFinance.com HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THESE LIMITATIONS AND EXCLUSIONS APPLY WITHOUT REGARD TO WHETHER THE DAMAGES ARISE FROM (1) BREACH OF CONTRACT, (2) BREACH OF WARRANTY, (3) STRICT LIABILITY, (4) NEGLIGENCE, (5) TORT, OR (6) ANY OTHER CAUSE OF ACTION, TO THE EXTENT SUCH EXCLUSION AND LIMITATIONS ARE NOT PROHIBITED BY APPLICABLE LAW. IF YOU ARE DISSATISFIED WITH THE SITE OR THE PRODUCTS OR REFERRAL SERVICE, YOU DO NOT AGREE WITH ANY PART OF THIS AGREEMENT, OR HAVE ANY OTHER DISPUTE OR CLAIM WITH OR AGAINST SavewellFinance.com WITH RESPECT THIS AGREEMENT, THE SITE OR THE PRODUCTS OR REFERRAL SERVICE, THEN YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING SUCH.</p>

            <h2 style={{ fontSize: '1.6rem', color: '#2c3e50', marginBottom: '15px' }}>Release</h2>
            <p>YOU HEREBY AGREE TO RELEASE, REMISE AND FOREVER DISCHARGE SavewellFinance.com AND ITS AFFILIATES, PARTNERS, SERVICE PROVIDERS, VENDORS, AND CONTRACTORS AND EACH OF THEIR RESPECTIVE AGENTS, OFFICERS, DIRECTORS, EMPLOYEES, AND ALL OTHER RELATED PERSONS OR ENTITIES FROM ANY AND ALL MANNER OF RIGHTS, CLAIMS, DEMANDS, COMPLAINTS, CAUSES OF ACTION, PROCEEDINGS, LIABILITIES, OBLIGATIONS, LEGAL FEES, COSTS, AND DISBURSEMENTS OF ANY NATURE WHATSOEVER, WHETHER KNOWN OR UNKNOWN, WHICH NOW OR HEREAFTER ARISE FROM, RELATE TO, OR ARE CONNECTED WITH YOUR USE OF THE SITE OR THE PRODUCTS OR REFERRAL SERVICE.</p>

            <h2 style={{ fontSize: '1.6rem', color: '#2c3e50', marginBottom: '15px' }}>Notice</h2>
            <p>SavewellFinance.com may provide you with notices, including those regarding changes to the Agreement, by either email, regular mail, or postings on the Site, Products or Referral Service. All notices to SavewellFinance.com must be emailed to <a href="mailto:support@savewellfinance.com" style={{ color: '#007BFF', textDecoration: 'underline' }}>support@savewellfinance.com</a>.</p>

            <h2 style={{ fontSize: '1.6rem', color: '#2c3e50', marginBottom: '15px' }}>Termination</h2>
            <p>You agree that SavewellFinance.com may, under certain circumstances and without prior notice, immediately terminate your access to the Site or Products or Referral Service. Cause for such termination shall include, but not be limited to: (i) breach or violation of the Agreement, other incorporated agreements or the Privacy Policy in any manner; (ii) requests by law enforcement or other government agencies; (iii) dismantling of the Site or discontinuance or material modification to the Products or Referral Service (or any part thereof); and (iv) unexpected technical or security issues or problems. You agree that all terminations for cause shall be made in SavewellFinance.com’s sole discretion, and SavewellFinance.com shall not be liable to you or any third party for any termination of the Site or access to the Products or Referral Service.</p>

            <h2 style={{ fontSize: '1.6rem', color: '#2c3e50', marginBottom: '15px' }}>Dealings with Third Parties</h2>
            <p>Your correspondence or business dealings with any third parties as a result of your visit to the Site and/or participation in the Products or Referral Service, including, but not limited to, business dealings with mortgage lenders or brokers, insurance agents or carriers, or any other terms, conditions, warranties, representations associated with such dealings, are solely between you and such third party. You agree that SavewellFinance.com shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or as the result of the presence of such third party on the Products or Referral Service.</p>

            <h2 style={{ fontSize: '1.6rem', color: '#2c3e50', marginBottom: '15px' }}>Disputes</h2>
            <p>This Agreement will be governed by and interpreted in accordance with the laws of the State of California, without regard to the conflicts of laws principles thereof, as such laws apply to contracts between California residents entered into and performed entirely within California. The United Nations Convention on Contracts for the International Sale of Goods does not apply to this Agreement. Any action or proceeding arising from or relating to this Agreement must be brought exclusively in a federal court in the Northern District of California or in a state court in San Francisco County, California. The parties have agreed that this Agreement will be written and construed in the English language.</p>

            <h2 style={{ fontSize: '1.6rem', color: '#2c3e50', marginBottom: '15px' }}>Modification to Products or Referral Service</h2>
            <p>SavewellFinance.com reserves the right at any time and from time to time to modify or discontinue, permanently or temporarily, the Products or Referral Service (or any part thereof) with or without notice. You agree that SavewellFinance.com shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Products or Referral Service.</p>

            <h2 style={{ fontSize: '1.6rem', color: '#2c3e50', marginBottom: '15px' }}>Waiver and Severability of Terms</h2>
            <p>The failure of SavewellFinance.com to exercise or enforce any right or provision of the Agreement shall not constitute a waiver of such right or provision. If any provision of the Agreement is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties’ intentions as reflected in the provision, and the other provisions of the Agreement remain in full force and effect.</p>

            <h2 style={{ fontSize: '1.6rem', color: '#2c3e50', marginBottom: '15px' }}>Disclosure of Your Information</h2>
            <p>You acknowledge, consent and agree that SavewellFinance.com may preserve, access, and disclose the information we collect about you if required to do so by law or in good faith belief that such access preservation or disclosure is reasonably necessary to: (i) abide by legal process; (ii) enforce the Agreement; (iii) respond to claims that any information or content violated the rights of any third parties; (iv) respond to your requests for customer service; or (v) protect the rights, property, or personal safety of SavewellFinance.com, its users and the public.</p>

            <h2 style={{ fontSize: '1.6rem', color: '#2c3e50', marginBottom: '15px' }}>Additional Terms</h2>
            <p>You acknowledge and agree that in addition to the terms of this Agreement, you may also be subject to additional terms and conditions that may apply when you use or purchase certain other SavewellFinance.com services, affiliate services, third party content or third party software.</p>

            <h2 style={{ fontSize: '1.6rem', color: '#2c3e50', marginBottom: '15px' }}>Survival</h2>
            <p>The following paragraphs shall survive termination or your refusal to continue to use the Service: 7, 8, 10, 11, 12, 13, 17, 22, and 23.</p>

            <h2 style={{ fontSize: '1.6rem', color: '#2c3e50', marginBottom: '15px' }}>Statute of Limitations</h2>
            <p>YOU AGREE THAT REGARDLESS OF ANY STATUTE OR LAW TO THE CONTRARY, ANY CLAIM OR CAUSE OF ACTION ARISING OUT OF RELATED TO USE OF THE PRODUCTS OR REFERRAL SERVICE OR THE AGREEMENT MUST BE FILED WITHIN ONE 3 MONTHS AFTER SUCH CLAIM OR CAUSE OF ACTION AROSE OR BE FOREVER BARRED.</p>

            <h2 style={{ fontSize: '1.6rem', color: '#2c3e50', marginBottom: '15px' }}>Do Not Call Over-ride Authorization</h2>
            <p>Submitting your personal information on a SavewellFinance.com inquiry form, landing page or calculator authorizes SavewellFinance.com or affiliated lenders to contact you about the product or service which you are inquiring about. This authorization overrides any prior preference placed with SavewellFinance.com or affiliated lenders and any other association or registration of any phone number on federal, state or internal “do not call” list(s) owned by the mortgage brokers or lenders.</p>

            <h2 style={{ fontSize: '1.6rem', color: '#2c3e50', marginBottom: '15px' }}>Newsletter subscriptions</h2>
            <p>When a user creates an account the default settings include receiving newsletters from SavewellFinance.com. Users can opt out of newsletters through the SavewellFinance.com subscription management functionality.</p>

            <p style={{ fontWeight: 'bold', marginTop: '40px' }}>PLEASE PRINT AND RETAIN A COPY OF THIS AGREEMENT FOR YOUR RECORDS.</p>
        </div>
    );
}

export default TermsOfUse;
